/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const APPLY_BODY = `实现 OpenSpec change 中的 tasks。

**语言**：默认使用简体中文输出进度和总结；命令、路径、代码标识符、API 名称、JSON/YAML key 保持英文。

**目标**

完成 tasks 文件中的待办任务，实现与 specs/design 一致；以每个任务的验证证据为完成标准，并通过即时更新与重读 tasks 文件保持进度和规划上下文同步。实现全部完成后，继续完成必要验证、文档、归档和 Git 提交，不停在代码修改或口头总结。

**选定 change**

用户指定则用之；只有一个 active change 时自动选用；能从对话上下文推断时用推断结果。以上都不成立时，用 \`openspec list --json\` 列出并让用户选择。开始时说明 "Using change: <name>" 及如何切换。

**获取上下文**

\`\`\`bash
openspec status --change "<name>" --json              # schemaName、changeRoot、actionContext
openspec instructions apply --change "<name>" --json  # contextFiles、任务清单、进度、动态指导
\`\`\`

- \`state: "blocked"\`（缺少 artifacts）：说明缺什么，建议先补齐，停止。
- \`state: "all_done"\`：跳过实现，直接进入下述“完成闭环”。
- **Workspace guard**：若 status 报告 \`actionContext.mode: "workspace-planning"\` 且 \`allowedEditRoots\` 为空，说明 full workspace apply is not supported in this slice——linked repos 与 folders 只作只读上下文，请用户通过显式 implementation workflow 选择 affected area，并在编辑任何文件前停止。

开始实现前，读取 \`contextFiles\` 中列出的所有文件（如 proposal/specs/design/tasks，具体以 CLI 输出为准，不要假设文件名）。

**执行循环**

1. 每轮开始前重读 tasks 文件，确认剩余工作、依赖和已记录状态；不要仅依赖此前对规划的记忆。
2. 主动识别适合 sub-agent 的独立切片。充分使用 sub-agent 执行互不冲突的调研、测试、验证和隔离实现；不得仅因主 agent 能自行完成就跳过明确可并行的工作。为每个 sub-agent 给出清晰范围、允许编辑路径和预期产出。共享文件、共享接口、架构决策、最终集成、验证、checkbox 和交付收尾由主 agent 负责。
3. 实现当前任务或并行批次，保持改动聚焦；审查并集成 sub-agent 结果。
4. 运行与当前任务直接相关的测试或具体检查，取得客观完成证据。
5. 仅在验证通过后，立即在 tasks 文件中把对应 \`- [ ]\` 改为 \`- [x]\`；随后立即重读 tasks 文件，核对最新进度、依赖和全部剩余任务，再选择下一项。

不得凭实现意图或部分测试勾选，不得把 checkbox 更新拖到会话末尾。持续执行，直到全部任务完成或出现无法自行解决的真实阻塞。

**不变量**

- 实现遵守 design.md 中已记录的决策；发现决策不可行时，先提出更新 artifacts，不绕过设计直接实现。
- 代码变更保持聚焦于任务范围。
- 错误优先自行修复并重试；连续失败、任务含义不清、或需要用户做方向性决策时才暂停。
- 需要用户确认时，使用所在环境的用户确认工具（如可用）或清晰提问，给出 2-3 个互斥选项、将推荐项放在最前，并说明各自影响或取舍；不要只问开放式的“下一步怎么办”。
- 保留工作区中不属于当前 change 的既有改动；归档和提交时只纳入当前范围，不回退或混入无关改动。

**完成闭环**

全部 tasks 验证完成后，默认继续完成以下动作；除非用户明确限定只实施不闭环，或仓库规则、权限、验证失败构成阻塞：

1. 重读 artifacts 和 tasks 文件，核对实现、规格与 checkbox 一致，并运行与变更风险匹配的最终验证。
2. 更新因行为、API、配置、迁移或使用方式变化而必须调整的文档；不要为无文档影响的变更制造占位内容。
3. 使用 OpenSpec archive workflow 同步 specs 并归档该 change；若 archive 出现需选择的分支，按上述方式提供确认选项。
4. 检查归档后的 Git diff，只 stage 当前 change 范围（禁止 \`git add -A\`），创建并核验 scoped Git commit。只有用户明确要求时才执行 push、发布或部署。

**完成或暂停时**

报告进度（N/M tasks complete）、验证结果、归档和 Git 状态。若暂停，说明具体阻塞及上述确认选项。表达格式遵循你所在环境的沟通规范。

**Fluid workflow**：本 skill 可以在任何时刻调用——部分实现后继续、与其他动作交错；实现中发现设计问题时更新 artifacts 再继续，没有 phase 锁定。`;

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement and close out an OpenSpec change through verified tasks, tasks.md checkpoints, sub-agent delegation, final validation, necessary documentation, archive, and a scoped Git commit. Use when the user wants to start or continue implementation or deliver a planned change.',
    instructions: APPLY_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI. Default commit closeout also requires a Git worktree; otherwise report the blocker.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement verified tasks and complete documentation, archive, and scoped Git commit closeout (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `${APPLY_BODY}

**Input**: Optionally specify a change name after \`/opsx:apply\` (e.g., \`/opsx:apply add-auth\`).`,
  };
}
