/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const ARCHIVE_BODY = `归档一个已完成的 OpenSpec change：评估 delta specs 是否需要同步到 main specs，然后把 change 目录移入 archive。

**语言**：默认使用简体中文输出说明和总结；命令、路径、代码标识符、API 名称、JSON/YAML key 保持英文。

**选定 change**

归档会移动目录，属于不可逆操作：执行前必须与用户确认选定的 change。用户明确指定则直接使用；否则用 \`openspec list --json\` 列出 active changes（含 schema 信息）让用户选择。

**前置检查**

\`\`\`bash
openspec status --change "<name>" --json
\`\`\`

- 若 \`actionContext.mode: "workspace-planning"\`：说明 workspace archive is not supported in this slice，停止。不要把 workspace change 移入 repo-local archive，也不要编辑 linked repos。
- 检查 artifacts 是否全部 \`done\`，并读取 tasks 文件统计未完成任务（\`- [ ]\`）。存在未完成项时，列出并让用户确认是否仍要归档——不阻塞，但要知情确认。

**Spec 同步评估**

若 \`artifactPaths.specs.existingOutputPaths\` 存在 delta specs：
- 对比每个 delta 与对应的 \`openspec/specs/<capability>/spec.md\`，总结将应用的变更（added/modified/removed/renamed）。
- 需要同步时询问："Sync now (recommended)" 或 "Archive without syncing"；已同步时提供 "Archive now" / "Sync anyway" / "Cancel"。
- 用户选择同步时，按 openspec-sync-specs 的合并语义执行（或委派给该 skill），然后继续归档。

**执行归档**

\`\`\`bash
mkdir -p "<planningHome.changesDir>/archive"
mv "<changeRoot>" "<planningHome.changesDir>/archive/YYYY-MM-DD-<name>"
\`\`\`

日期使用当天日期。目标目录已存在时报错并建议处理方式（改名或换日期），不要覆盖。\`.openspec.yaml\` 随目录一起移动。

**完成时**

报告 change 名称、归档位置、specs 是否已同步、以及任何被用户确认跳过的警告。表达格式遵循你所在环境的沟通规范。`;

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: ARCHIVE_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `${ARCHIVE_BODY}

**Input**: Optionally specify a change name after \`/opsx:archive\` (e.g., \`/opsx:archive add-auth\`).`,
  };
}
