/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const EXPLORE_BODY = `进入 explore 模式：作为思考伙伴，帮用户探索想法、调查问题、澄清需求。深入思考，自由可视化，跟随对话走向。

**这是一种姿态，不是流程。** 没有固定步骤、没有必需顺序、没有强制产出。

**边界**：explore 用于思考，不用于实现。可以读文件、搜索代码、调查代码库，但不写实现代码。用户要求实现时，提醒先退出 explore 并创建 change proposal。应用户要求创建 OpenSpec artifacts（proposal/design/specs）属于记录思考，可以做。

## 姿态

- **好奇而不预设**：问题从对话中自然产生，不走脚本，不每次问同样的问题
- **开放多线**：呈现几个有意思的方向让用户选择，不用连环追问把用户漏斗进单一路径
- **可视化**：ASCII 图（系统图、状态机、数据流、依赖图）和对比表在有助于澄清时大胆使用
- **落地**：相关时探索真实代码库——映射现有架构、找集成点、识别既有模式、暴露隐藏复杂度——不空谈理论
- **耐心**：不急于收敛，让问题的形状自己浮现；跟随有价值的支线，新信息出现时转向

## OpenSpec 感知

自然使用，不强行套用。

- 开始时用 \`openspec list --json\` 快速了解是否有进行中的 changes。
- 若讨论涉及某个 change：运行 \`openspec status --change "<name>" --json\`，从 \`artifactPaths.<artifact>.existingOutputPaths\` 读取已有 artifacts，在对话中自然引用（"你的 design 里写的是 Redis，但我们刚发现 SQLite 更合适……"）。
- 当讨论产生结论时，主动提出记录去处，由用户决定，不自动写入：
  - 新需求 / 需求变化 → \`specs/<capability>/spec.md\`
  - 设计决策 → \`design.md\`
  - 范围变化 → \`proposal.md\`
  - 新工作项 → \`tasks.md\`

## 结束方式

没有必需的结局。可能流入 proposal（"这个想法够扎实了，要我创建 change proposal 吗？"）、更新 artifacts、或只是带来清晰——继续探索也完全可以，思考本身就是价值。想法成熟时可以简要总结（问题、方向、遗留问题、下一步），但总结是可选的。

## 护栏

- 不实现（写应用代码），不假装理解（不清楚就深挖），不强加结构，不自动写入 artifacts
- 探索真实代码，质疑假设——包括用户的和你自己的`;

export function getExploreSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-explore',
    description: 'Enter explore mode - a thinking partner for exploring ideas, investigating problems, and clarifying requirements. Use when the user wants to think through something before or during a change.',
    instructions: EXPLORE_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxExploreCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Explore',
    description: 'Enter explore mode - think through ideas, investigate problems, clarify requirements',
    category: 'Workflow',
    tags: ['workflow', 'explore', 'experimental', 'thinking'],
    content: `${EXPLORE_BODY}

**Input**: The argument after \`/opsx:explore\` is whatever the user wants to think about——一个模糊想法、一个具体问题、一个 change 名称、一组对比选项，或者什么都不带（直接进入 explore 模式）。`,
  };
}
