/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const PROPOSE_BODY = `提出一个新的 OpenSpec change：创建 change 并生成实现前所需的全部规划 artifacts（proposal / specs / design / tasks，以 schema 为准）。

**语言**：产出物默认使用简体中文；命令、路径、代码标识符、API 名称、JSON/YAML key 保持英文。

**目标**

\`openspec status --change "<name>" --json\` 中 \`applyRequires\` 列出的所有 artifact 状态为 \`done\`，且内容质量足以直接开始实现。

**工具**

\`\`\`bash
openspec new change "<name>"                                  # 创建 change 脚手架
openspec status --change "<name>" --json                      # artifact 依赖图与状态（ground truth）
openspec instructions <artifact-id> --change "<name>" --json  # 单个 artifact 的写作指导
\`\`\`

status 返回 \`artifacts\`（各 artifact 的状态与依赖）、\`applyRequires\`、\`planningHome\`/\`changeRoot\`/\`artifactPaths\`（路径上下文，不要假设 repo-local 路径）。
instructions 返回 \`template\`（输出结构）、\`instruction\`（该 artifact 的具体要求）、\`resolvedOutputPath\`（写入路径）、\`dependencies\`（写作前应读取的已完成 artifact）、\`context\`/\`rules\`（对你的约束——不要复制进产出文件）。

**工作方式**

1. 明确要做什么。如果用户没有说清楚要构建或修复什么，先问清再开始；从描述派生 kebab-case 名称（如 "add user authentication" → \`add-user-auth\`）。同名 change 已存在时，确认是继续它还是新建。
2. 先判断变更的架构显著性（是否跨模块、是否改共享契约、是否涉及迁移/安全/性能）。显著变更先阅读本 skill 的 \`references/architecture-guidance.md\`（如可用）并检查现有 specs 与代码模式；简单变更快速推进，artifact 保持极简，不为凑格式编造内容。
3. 创建 change，然后按依赖图产出 artifacts。编排由你决定：依赖已满足的 artifact 可以并行创建（如 specs 和 design 都只依赖 proposal），无需在每个 artifact 之后重复查询状态；收尾时用一次 status 校验 \`applyRequires\` 全部 done。

**不变量**

- 写每个 artifact 前，先读取它的依赖 artifact。
- delta spec 的结构化格式不可改动（\`## ADDED/MODIFIED/REMOVED/RENAMED Requirements\`、\`### Requirement:\`、\`#### Scenario:\` 四级井号）——archive 合并依赖这些解析。
- tasks.md 的任务必须是 \`- [ ]\` checkbox，apply 阶段靠它跟踪进度。
- 关键歧义（会导致方向性返工）先问用户；其余合理决策自行做出，保持推进。

**完成时**

报告 change 名称与位置、创建的 artifacts、下一步（运行 /opsx:apply 或直接要求实现）。表达格式遵循你所在环境的沟通规范。`;

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: PROPOSE_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `${PROPOSE_BODY}

**Input**: The argument after \`/opsx:propose\` is the change name (kebab-case), OR a description of what the user wants to build.`,
  };
}
