/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const SYNC_BODY = `把 change 的 delta specs 同步到 main specs。

这是 **agent-driven** 操作：你读取 delta specs，直接编辑 main specs 完成智能合并（例如只添加一个 scenario 而无需复制整个 requirement）。change 保持 active，实现完成后再 archive。

**语言**：默认使用简体中文输出说明和总结；命令、路径、代码标识符、API 名称、JSON/YAML key 保持英文。

**选定 change**

用户指定则用之；只有一个含 delta specs 的 active change 时自动选用并告知；否则用 \`openspec list --json\` 列出让用户选择。

**获取上下文**

\`\`\`bash
openspec status --change "<name>" --json
\`\`\`

- 若 \`actionContext.mode: "workspace-planning"\`：说明 workspace spec sync is not supported in this slice，停止。不要回退到 repo-local 路径或编辑 linked repos。
- delta spec 文件列表取自 \`artifactPaths.specs.existingOutputPaths\`；没有 delta specs 时告知并停止。

**合并语义**

对每个 delta spec，目标是 \`openspec/specs/<capability>/spec.md\`。先读 delta 和 main spec，再应用：

- **ADDED Requirements**：main spec 中不存在则新增；已存在则更新为 delta 内容（视为隐式 MODIFIED）。
- **MODIFIED Requirements**：定位既有 requirement 应用变化——可以是新增 scenario、修改 scenario 或改描述；delta 未提及的内容保持不变。
- **REMOVED Requirements**：删除整个 requirement block。
- **RENAMED Requirements**：按 FROM:/TO: 重命名。
- capability 的 main spec 不存在时新建（Purpose 可简短，标注 TBD）。

Delta 格式参考：

\`\`\`markdown
## ADDED Requirements

### Requirement: New Feature
The system SHALL do something new.

#### Scenario: Basic case
- **WHEN** user does X
- **THEN** system does Y

## RENAMED Requirements

- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

**核心原则：智能合并。** Delta 表达的是意图，不是整体替换。用你的判断合理合并；保留 delta 未提及的既有内容；操作应幂等（重复执行结果一致）。不确定时先问再改。

**完成时**

按 capability 总结应用的变更（requirements added/modified/removed/renamed）。表达格式遵循你所在环境的沟通规范。`;

export function getSyncSpecsSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-sync-specs',
    description: 'Sync delta specs from a change to main specs. Use when the user wants to update main specs with changes from a delta spec, without archiving the change.',
    instructions: SYNC_BODY,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxSyncCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Sync',
    description: 'Sync delta specs from a change to main specs',
    category: 'Workflow',
    tags: ['workflow', 'specs', 'experimental'],
    content: `${SYNC_BODY}

**Input**: Optionally specify a change name after \`/opsx:sync\` (e.g., \`/opsx:sync add-auth\`).`,
  };
}
